language: python

python:

  - "2.7"

  - "3.5"

  - "3.6.1"

before_script:
  - pip install twine
  - python setup.py sdist bdist_wheel

deploy:
  provider: pypi
  user: "san3107"
  password: "Sanjeev@pip"
  distributions: "sdist bdist_wheel" # Your distributions here
  on:
    branch: master

script:
  - twine upload dist/*